### ISSUE TITLE
离线缓存视频 第二次进入播放页报错 Another SimpleCache instance uses the folder: 

### ISSUE THREAD

**Issue by SuitG** [yangchaojiang/yjPlay#132]
07-03 17:17:06.046 14046-14046/chuangyuan.xiangjiang.yjplay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chuangyuan.xiangjiang.yjplay, PID: 14046
    java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /storage/emulated/0/Android/data/chuangyuan.xiangjiang.yjplay/files/media
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:124)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:111)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:96)
        at chuangyuan.ycj.videolibrary.factory.DefaultCacheDataSourceFactory.<init>(DefaultCacheDataSourceFactory.java:74)
        at chuangyuan.ycj.videolibrary.factory.DefaultCacheDataSourceFactory.<init>(DefaultCacheDataSourceFactory.java:55)
        at chuangyuan.ycj.yjplay.offline.OfficeDataSource.getDataSourceFactory(OfficeDataSource.java:32)
        at chuangyuan.ycj.videolibrary.video.MediaSourceBuilder.getDataSource(MediaSourceBuilder.java:196)
        at chuangyuan.ycj.videolibrary.whole.WholeMediaSource.initMediaSource(WholeMediaSource.java:57)
        at chuangyuan.ycj.videolibrary.video.MediaSourceBuilder.setMediaUri(MediaSourceBuilder.java:74)
        at chuangyuan.ycj.videolibrary.video.ExoUserPlayer.setPlayUri(ExoUserPlayer.java:474)
        at chuangyuan.ycj.videolibrary.video.ExoUserPlayer.setPlayUri(ExoUserPlayer.java:389)
        at chuangyuan.ycj.yjplay.offline.OfficeDetailedActivity$1.onClick(OfficeDetailedActivity.java:47)
        at android.view.View.performClick(View.java:5673)
        at android.view.View$PerformClick.run(View.java:22513)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by yangchaojiang** [comment]
demo 也是吗？

**Comment by yangchaojiang** [comment]
我测试demo ok . 你是使用之前的版本自定义缓存？？

**Comment by SuitG** [comment]
是的，我是直接下载的demo的代码直接运行报错的。

**Comment by yangchaojiang** [comment]
版本2.1.83已修复，谢谢反馈/

**Comment by SuitG** [comment]
还有个问题，播放本地.ts文件好像无法获取到视频时长

**Comment by yangchaojiang** [comment]
2.2.17  可以获取到
![default](https://user-images.githubusercontent.com/13806413/44438203-a7c15700-a5f0-11e8-82dd-8ec69db6c82a.png)
![default](https://user-images.githubusercontent.com/13806413/44438208-adb73800-a5f0-11e8-96a9-449e73dc31cf.png)

**Comment by helixs** [comment]
我出现了这个问题。最新版OfficeDetailedActivity退出页面就会。调用ondestory

**Comment by Danniel-yan** [comment]
> 我出现了这个问题。最新版OfficeDetailedActivity退出页面就会。调用ondestory
> 
> lockedCacheDirs始终没有清除。。。。

请问这个返回闪退的问题怎么解决的？

**Comment by Danniel-yan** [comment]
将Demo中的CacheDataSourceFactory参数 cache抽离成单例就可以了
