### ISSUE TITLE
播放m3u8时，activity回调onPause和onDestorey会空指针

### ISSUE THREAD

**Issue by diamondlin2016** [yangchaojiang/yjPlay#137]
问题现象：播放m3u8时，activity回调onPause和onDestorey会空指针。
错误日志：日志如下
版本：com.ycjiang:VideoPlayModule:2.1.83

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.upstream.Loader.release()' on a null object reference
                                                                     at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.release(DefaultHlsPlaylistTracker.java:113)
                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaSource.releaseSourceInternal(HlsMediaSource.java:404)
                                                                     at com.google.android.exoplayer2.source.BaseMediaSource.releaseSource(BaseMediaSource.java:150)
                                                                     at chuangyuan.ycj.videolibrary.video.MediaSourceBuilder.release(MediaSourceBuilder.java:219)
                                                                     at chuangyuan.ycj.videolibrary.video.ExoUserPlayer.releasePlayers(ExoUserPlayer.java:254)
                                                                     at chuangyuan.ycj.videolibrary.video.ExoUserPlayer.onPause(ExoUserPlayer.java:224)
                                                                     at chuangyuan.ycj.videolibrary.video.ManualPlayer.onPause(ManualPlayer.java:125)
                                                                     at com.live.xxlive.ui.TvPlayActivity.onPause(TvPlayActivity.java:117)

**Comment by yangchaojiang** [comment]
我在开发版已经修复，最近下一个版本，

**Comment by yangchaojiang** [comment]
版本2.185 已修改
