### ISSUE TITLE
本地播放不支持h264吗？

### ISSUE THREAD

**Issue by jinyingfeng** [yangchaojiang/yjPlay#142]
问题现象：本地文件h264格式无法播放，3gp可以
错误日志：xxxxxx

**Comment by yangchaojiang** [comment]
你的h264 是MP4 吗

**Comment by yangchaojiang** [comment]
。。。。支持是 视频编码为h264   不是h264的格式。  视频文件不能直接后缀的，没有也没有，编码方式没有变

**Comment by jinyingfeng** [comment]
是h264编码的视频流，
Video: MPEG4 Video (H264) 1920x1080 25fps [V: h264 baseline L4.1, yuv420p, 1920x1080]
General
Format                         : AVC
Format/Info                    : Advanced Video Codec
File size                      : 4.03 MiB

Video
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Baseline@L4.1
Format settings, CABAC         : No
Format settings, ReFrames      : 1 frame
Format settings, GOP           : M=1, N=20
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive

这个是第三方播放器的信息

**Comment by yangchaojiang** [comment]
Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
I think you're just trying to play a video that exceeds the capabilities of the device. In the bug report:

MediaCodecInfo: NoSupport [size.support, 1920x1080] [OMX.qcom.video.decoder.avc, video/avc] [otus_ds, MotoE2, motorola, 22]
Note that the video you're trying to play has 4x the number of pixels as the display. It's quite common for devices to only be able to decode approximately 1x the number of pixels as the display.

**Comment by yangchaojiang** [comment]
Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
是报这个错误吧

**Comment by yangchaojiang** [comment]
我想你只是想播放超出设备功能的视频。在错误报告中：
请注意，您尝试播放的视频的像素数是显示器的4倍。设备通常只能解码大约1倍的像素数作为显示器。
[exoPlayer的错误](https://github.com/google/ExoPlayer/issues/3282)

**Comment by jinyingfeng** [comment]
在日志里发现
 MountPointManager, isExternalMountPath ,path =/storage/emulated/0
    MountPointManager, isExternalFile,ret = false
    IconManager, getIcon,isExternal =false
    FileInfo, getFileMimeType,service.
    FileInfo, getMimeType fileName=2018-07-12-10-23-30.h264,extension = h264
    FileInfo, getMimeType mimeType =null
    FileInfo, getFileMimeType, mimetype is : unknown_ext_mimeType
    IconManager, getIcon imimeType =unknown_ext_mimeType
demo显示：播放异常，视频地址异常，或者网络不可用

**Comment by jinyingfeng** [comment]
我直接改demo的 MainDetailedActivity类oncreate
exoPlayerManager.setPlayUri("/sdcard/Movies/VideoRecord/2018-07-13-11-06-50.h264");
        //开始启动播放视频
        exoPlayerManager.startPlayer();

**Comment by yangchaojiang** [comment]
demo视频发一下。

**Comment by jinyingfeng** [comment]
刚才调试发现这个异常log
07-18 15:16:01.933 13800-13903/chuangyuan.xiangjiang.yjplay E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException: Top bit not zero: -8246864716185210176
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedLongToLong(ParsableByteArray.java:415)
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:112)
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:73)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:270)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:915)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:849)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
07-18 15:16:01.938 13800-13900/chuangyuan.xiangjiang.yjplay E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -8246864716185210176
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:342)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalStateException: Top bit not zero: -8246864716185210176
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedLongToLong(ParsableByteArray.java:415)
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:112)
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:73)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:270)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:915)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:849)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
07-18 15:16:01.950 13800-13831/chuangyuan.xiangjiang.yjplay D/Surface: Surface::setBuffersDimensions(this=0x7f7ae22a00,w=1080,h=1920)
07-18 15:16:01.954 13800-13800/chuangyuan.xiangjiang.yjplay E/chuangyuan.ycj.videolibrary.video.ExoUserPlayer: onPlayerError:null
07-18 15:16:01.960 13800-13800/chuangyuan.xiangjiang.yjplay D/chuangyuan.ycj.videolibrary.video.ExoUserPlayer: onPlayerStateChanged:1+playWhenReady:true
    onPlayerStateChanged::网络状态差，请检查网络。。。
07-18 15:16:01.975 13800-13831/chuangyuan.xiangjiang.yjplay D/Surface: Surface::setBuffersDimensions(this=0x7f7ae22a00,w=1080,h=1920)

**Comment by jinyingfeng** [comment]
测试机无法上网

**Comment by yangchaojiang** [comment]
我要播放的视频文件呀。 @jinyingfeng  :joy: :joy: :joy: :joy:

**Comment by jinyingfeng** [comment]
https://pan.baidu.com/s/1IRXivGV3dUwUng0_5ZxENg

**Comment by jinyingfeng** [comment]
我想你只是想播放超出设备功能的视频。在错误报告中：
请注意，您尝试播放的视频的像素数是显示器的4倍。设备通常只能解码大约1倍的像素数作为显示器。
exoPlayer的错误
