### ISSUE TITLE
重复切屏出现播放异常

### ISSUE THREAD

**Issue by JamChanGitHub** [yangchaojiang/yjPlay#175]
E/ExoPlayerImplInternal: Internal runtime error.
                                                                                  java.lang.IllegalStateException
                                                                                      at android.media.MediaCodec.releaseOutputBuffer(Native Method)
                                                                                      at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2701)
                                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.renderOutputBufferV21(MediaCodecVideoRenderer.java:775)
                                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:596)
                                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068)
                                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)

 E/ExoPlayerImplInternal: Stop failed.
                                                                                  java.lang.IllegalStateException
                                                                                      at android.media.MediaCodec.native_stop(Native Method)
                                                                                      at android.media.MediaCodec.stop(MediaCodec.java:2032)
                                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:512)
                                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:439)
                                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:468)
                                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:341)
                                                                                      at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:772)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)****

**Comment by JamChanGitHub** [comment]
![image](https://user-images.githubusercontent.com/18138936/45207594-f17d9300-b2ba-11e8-9a88-39362bcb4d94.png)
![image](https://user-images.githubusercontent.com/18138936/45207602-f6dadd80-b2ba-11e8-8bb4-ba589c86bbf6.png)
急急急，希望早点回复

**Comment by yangchaojiang** [comment]
？？？？

**Comment by yangchaojiang** [comment]
切屏

**Comment by JamChanGitHub** [comment]
对，切横竖屏报这个错，屏幕黑屏，提示错误“播放异常,视频地址异常，或者网络不可用”

**Comment by yangchaojiang** [comment]
在activity节点 加上“android:configChanges="orientation|keyboardHidden|screenSize"”
 如下实例：
        <activity android:name="chuangyuan.ycj.yjplay.MainListActivity"
         android:configChanges="orientation|keyboardHidden|screenSize"
         android:screenOrientation="portrait">

**Comment by yangchaojiang** [comment]
@Override
            public void onConfigurationChanged(Configuration newConfig) {
                exoPlayerManager.onConfigurationChanged(newConfig);//横竖屏切换
                super.onConfigurationChanged(newConfig);
            }

**Comment by JamChanGitHub** [comment]
![image](https://user-images.githubusercontent.com/18138936/45209590-f6911100-b2bf-11e8-847e-8dc24971d300.png)
已经加了

**Comment by yangchaojiang** [comment]
acitivity 周期实现

**Comment by yangchaojiang** [comment]
您使用版本是多少

**Comment by JamChanGitHub** [comment]
![image](https://user-images.githubusercontent.com/18138936/45209735-4a035f00-b2c0-11e8-8bda-372e17926ba2.png)
这个也加了，切换会自动暂停，然后提示错误

**Comment by JamChanGitHub** [comment]
我是导的源码的，大概今年二月份导的，请求源码哪里可以看版本，我忘记当时导入的时候是什么版本了

**Comment by JamChanGitHub** [comment]
之前用这个版本在另外一个项目上是没问题的，但是现在这个项目就出现这个问题

**Comment by yangchaojiang** [comment]
那你检查你的代码。你是使用同一个版本代码，一个没问题。，一个有问题哦
