### ISSUE TITLE
java.lang.IllegalStateException: 没有找到 当前视频类型,或者不支持当前类型，依赖完整版

### ISSUE THREAD

**Issue by RiceRichhonour** [yangchaojiang/yjPlay#191]
java.lang.IllegalStateException: 没有找到 当前视频类型,或者不支持当前类型，依赖完整版

，已经配置了完整版，但是播放m3u8的时候，崩溃报错了。

rtmp  flv  mp4都正常。

**Comment by yangchaojiang** [comment]
连接。后缀名是.m3u8 嘛

**Comment by RiceRichhonour** [comment]
用的是您demo里面的链接。

**Comment by RiceRichhonour** [comment]
.setPlayUri("http://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1.m3u8")， 哦，我换了个，

 设置的是默认的数据源 DefaultHttpDataSourceFactory    rtmp的那个数据源设置了下也不行。望回复，谢谢

**Comment by RiceRichhonour** [comment]
> 连接。后缀名是.m3u8 嘛

.setPlayUri("http://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1.m3u8")， 哦，我换了个，

设置的是默认的数据源 DefaultHttpDataSourceFactory rtmp的那个数据源设置了下也不行。望回复，谢谢

**Comment by RiceRichhonour** [comment]
> 连接。后缀名是.m3u8 嘛

您demo里面的我也试了，也不行，希望指导一下，谢谢。

以下为依赖。
  implementation 'com.google.android.exoplayer:extension-okhttp:2.9.0'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.9.0'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.8.2'

  //  implementation 'com.google.android.exoplayer:extension-cast:2.8.2'
    implementation 'com.google.android.exoplayer:extension-ima:2.8.2'
    implementation 'com.google.android.exoplayer:extension-leanback:2.8.2'

    implementation 'com.ycjiang:VideoPlayModule:2.3.0'

**Comment by yangchaojiang** [comment]
```
        return new DefaultHttpDataSourceFactory(context.getPackageName(),null ,DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,true);
```
还有使用rtmp 自己需要实例化数据源的。DefaultHttpDataSourceFactory 不支持的

**Comment by yangchaojiang** [comment]
实例化的，。协议是不同的 rtmp 协议和http协议
````
 return new RtmpDataSourceFactory();
````

**Comment by RiceRichhonour** [comment]
> 实例化的，。协议是不同的 rtmp 协议和http协议
> 
> ```
>  return new RtmpDataSourceFactory();
> ```
rtmp这个我已经实例化了  return new RtmpDataSourceFactory();  可以实现，

我就是不太理解，m3u8实例化哪种数据源，默认的我测试不可行，也就是

return new DefaultHttpDataSourceFactory(context.getPackageName(),null ,DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,true);

**Comment by yangchaojiang** [comment]
我测试没问题啊。  但是尼连接的m3u8 不是稳定。容易断。我给你一个连接
```
http://dlhls.cdn.zhanqi.tv/zqlive/35180_KUDhx.m3u8
```

**Comment by RiceRichhonour** [comment]
> 我测试没问题啊。 但是尼连接的m3u8 不是稳定。容易断。我给你一个连接
> 
> ```
> http://dlhls.cdn.zhanqi.tv/zqlive/35180_KUDhx.m3u8
> ```

谢谢大佬的回复，但是我现在是其他的都可行，就m3u8，运行，直接崩溃，说不支持，运行了下您的链接。

 ```
Caused by: java.lang.IllegalStateException: 没有找到 当前视频类型,或者不支持当前类型，依赖完整版
        at chuangyuan.ycj.videolibrary.d.d.b(Unknown Source)
        at chuangyuan.ycj.videolibrary.d.d.a(Unknown Source)
        at chuangyuan.ycj.videolibrary.d.f$a.a(Unknown Source)
        at chuangyuan.ycj.videolibrary.d.f$a.b(Unknown Source)
```

**Comment by yangchaojiang** [comment]
检查你有没有重复依赖什么？ 我gitbub 下载的项目也可以的
