### ISSUE TITLE
发生空指针异常，使用版本：2.1.91

### ISSUE THREAD

**Issue by I18N486** [yangchaojiang/yjPlay#196]
10-22 13:49:59.887 5452-5452/com.iflytek.huiyisystem E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.SimpleExoPlayer.getCurrentPosition()' on a null object reference
                                                                             at chuangyuan.ycj.videolibrary.video.GestureVideoPlayer$PlayerGestureListener.onScroll(GestureVideoPlayer.java:355)
                                                                             at android.view.GestureDetector.onTouchEvent(GestureDetector.java:611)
                                                                             at chuangyuan.ycj.videolibrary.video.GestureVideoPlayer$1.onTouch(GestureVideoPlayer.java:299)
                                                                             at android.view.View.dispatchTouchEvent(View.java:11773)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                             at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3321)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                             at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
                                                                             at android.view.View.dispatchPointerEvent(View.java:12016)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4809)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4623)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4180)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4188)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4364)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4180)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4188)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6682)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6656)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6617)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6785)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                                                                             at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                             at android.os.MessageQueue.next(MessageQueue.java:325)
                                                                             at android.os.Looper.loop(Looper.java:142)
                                                                         	at android.app.ActivityThread.main(ActivityThread
10-22 13:49:59.888 5452-5452/com.iflytek.huiyisystem E/AndroidRuntime: FATAL EXCEPTION: main

崩溃日志如上；发生情形：点击播放之后再暂停，同时有一个线程一直获取播放进度，getcurrentPosition

**Comment by yangchaojiang** [comment]
请升级版本号。最新版本。修改策略
