### ISSUE TITLE
OnEndGestureListener类找不到

### ISSUE THREAD

**Issue by silence17** [yangchaojiang/yjPlay#208]
下载2.3.12，OnEndGestureListener类找不到导致编译失败，请问我下载版本的问题吗

**Comment by jayxioresearch** [comment]
我也遇到了同样的问题。Android Studio 3.2.1 on macOS High Sierra (version 10.13.5)

**Comment by yangchaojiang** [comment]
我看一下。不好意思。

**Comment by yangchaojiang** [comment]
被忽略了。编译时候。文件已经上传。谢谢你的支持

**Comment by silence17** [comment]
项目里集成老版本的感觉很强大。

但我在用老版本的时候遇到一个问题，我在activity的viewpager中添加了该控件（商品详情的轮播图第一页是视频，以后是图片）点击图片进入第二个activity仍然集成了该控件，但是播放之后点击返回就报空指针这是我报的错，请问是我集成的问题吗。

我在activity的生命周期都调用了相应的方法
Process: cn.hhealth.shop, PID: 14892
                                                                 java.lang.RuntimeException: Unable to resume activity {cn.hhealth.shop/cn.hhealth.shop.activity.ProductDetailActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean chuangyuan.ycj.videolibrary.listener.ExoPlayerViewListener.isList()' on a null object reference
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean chuangyuan.ycj.videolibrary.listener.ExoPlayerViewListener.isList()' on a null object reference
                                                                     at chuangyuan.ycj.videolibrary.video.ManualPlayer.onResume(ManualPlayer.java:124)
                                                                     at chuangyuan.ycj.videolibrary.video.VideoPlayerManager.onResume(VideoPlayerManager.java:67)
                                                                     at cn.hhealth.shop.activity.ProductDetailActivity.onResume(ProductDetailActivity.java:167)
                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
                                                                     at android.app.Activity.performResume(Activity.java:7361)
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                     at android.os.Looper.loop(Looper.java:164) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6944) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by silence17** [comment]
我编译新版本的时候，PlayerNotificationManager中的资源文件貌似您没有提交，还请你看一下

 R.drawable.exo_notification_play,
R.drawable.exo_notification_pause,
R.drawable.exo_notification_stop,
。。。

**Comment by yangchaojiang** [comment]
好的 ，更新一下

**Comment by yangchaojiang** [comment]
你试一下新版本是由存在。 因为新版。内部代码实现方式有和老板不一样

**Comment by silence17** [comment]
好的，谢谢你的及时回复

**Comment by yangchaojiang** [comment]
。上午有空  下午要出去一趟。练车

**Comment by silence17** [comment]
OK，我学习一下

**Comment by silence17** [comment]
> 你试一下新版本是由存在。 因为新版。内部代码实现方式有和老板不一样
