### ISSUE TITLE
从详情返回列表能否不释放资源，并且默认不播放

### ISSUE THREAD

**Issue by silence17** [yangchaojiang/yjPlay#215]
你好，我在您的VideoPlayerManager中摘的一个方法，我从详情返回列表播放的view，最后一个参数isEnd 如果是true就释放资源，是false就继续播放。但是我现在需要从详情返回列表默认不播放，也不释放资源。请问有其他的方法能调用吗

    /*****
     *@param  oldPlayerView 旧的view
     * @param   currPosition  当前进度
     * @param      isEnd  是否播放完毕
     ****/
    public void switchTargetViewResult(@NonNull VideoPlayerView oldPlayerView, long currPosition, boolean isEnd) {
        ExoUserPlayer manualPlayer = getVideoPlayer();
        if (manualPlayer != null) {
            manualPlayer.setPosition(currPosition);
            manualPlayer.switchTargetView(oldPlayerView);
            if (isEnd) {
                oldPlayerView.resets();
                manualPlayer.reset();
            } else {
                manualPlayer.resetList();
                manualPlayer.startVideo();
            }
        }
    }

**Comment by yangchaojiang** [comment]
是重置，不是释放，有的东西做一些相应复原

**Comment by silence17** [comment]
哦哦，请问您遇到过这个错误吗，现在不能播放视频了呢
46:15.381 13893-14551/cn.hhealth.shop E/ExoPlayerImplInternal: Source error.
                                                                        com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: 715: open failed: ENOENT (No such file or directory)
                                                                            at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
                                                                            at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
                                                                            at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                            at java.lang.Thread.run(Thread.java:764)
                                                                         Caused by: java.io.FileNotFoundException: 715: open failed: ENOENT (No such file or directory)
                                                                            at libcore.io.IoBridge.open(IoBridge.java:512)
                                                                            at java.io.RandomAccessFile.<init>(RandomAccessFile.java:255)
                                                                            at java.io.RandomAccessFile.<init>(RandomAccessFile.java:136)
                                                                            at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
                                                                            at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
                                                                            at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                            at java.lang.Thread.run(Thread.java:764) 
                                                                         Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                            at libcore.io.Linux.open(Native Method)
                                                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:207)
                                                                            at libcore.io.IoBridge.open(IoBridge.java:498)
                                                                            at java.io.RandomAccessFile.<init>(RandomAccessFile.java:255) 
                                                                            at java.io.RandomAccessFile.<init>(RandomAccessFile.java:136) 
                                                                            at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65) 
                                                                            at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
                                                                            at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                            at java.lang.Thread.run(Thread.java:764)

**Comment by silence17** [comment]
不好意思找到原因了，谢谢
