### ISSUE TITLE
RtmpClient$RtmpIOException

### ISSUE THREAD

**Issue by kedongjun** [yangchaojiang/yjPlay#233]
11:07:10.051 30938-30962/com.app.kent.kkmovies E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:60)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
01-16 11:07:10.061 30938-30938/com.app.kent.kkmovies E/chuangyuan.ycj.videolibrary.video.ExoUserPlayer: onPlayerError:net.butterflytv.rtmp_client.RtmpClient$RtmpIOException

出现以上报错，怎么解决？？

**Comment by yangchaojiang** [comment]
报错版本是多少？

**Comment by yangchaojiang** [comment]
你的视频流Rtmp协议的。 你应引用完整版本 了吗

**Comment by kedongjun** [comment]
我引用了这个2.3.20完整版本，如下：
 implementation 'com.ycjiang:VideoPlayModule:2.3.20'

**Comment by yangchaojiang** [comment]
不好意思久等了。 2.3.30

**Comment by yangchaojiang** [comment]
exoplayer 更新了
