### ISSUE TITLE
最新版 出现如下问题

### ISSUE THREAD

**Issue by molele2** [yangchaojiang/yjPlay#237]
Caused by: java.lang.IllegalArgumentException: sizeMultiplier must be between 0 and 1
        at com.bumptech.glide.RequestBuilder.thumbnail(RequestBuilder.java:312)
        at com.warunion.example.video.AddVideoActivity.onCreate(AddVideoActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:7136)

**Comment by molele2** [comment]
是加载图片的glide引起的
