### ISSUE TITLE
Demo的离线缓存播放界面返回之后会闪退

### ISSUE THREAD

**Issue by NSocket** [yangchaojiang/yjPlay#265]
这是MIUI系统抓到的异常
java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /storage/emulated/0/Android/data/chuangyuan.xiangjiang.yjplay/files/media
	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:125)
	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:112)
	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:97)
	at chuangyuan.ycj.videolibrary.factory.DefaultCacheDataSourceFactory.<init>(DefaultCacheDataSourceFactory.java:80)
	at chuangyuan.ycj.videolibrary.factory.DefaultCacheDataSourceFactory.<init>(DefaultCacheDataSourceFactory.java:59)
	at chuangyuan.ycj.yjplay.data.OfficeDataSource.getDataSourceFactory(OfficeDataSource.java:32)
	at chuangyuan.ycj.videolibrary.video.MediaSourceBuilder.destroy(MediaSourceBuilder.java:235)
	at chuangyuan.ycj.videolibrary.video.ExoUserPlayer.onDestroy(ExoUserPlayer.java:202)
	at chuangyuan.ycj.yjplay.offline.OfficeDetailedActivity.onBackPressed(OfficeDetailedActivity.java:103)
	at android.app.Activity.onKeyUp(Activity.java:3147)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2739)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3430)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:352)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5221)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5089)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4608)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4661)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4767)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4635)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4824)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4608)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4661)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4635)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4608)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4661)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4800)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4963)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2584)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2094)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2085)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2561)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:332)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by yangchaojiang** [comment]
使用没有缓存类关闭哦 ，需要自己处理的
SimpleCache  有锁的
