### ISSUE TITLE
列表播放自定义手势布局空指针

### ISSUE THREAD

**Issue by wsty** [yangchaojiang/yjPlay#37]
Process: chuangyuan.xiangjiang.yjplay, PID: 5759
                                                                            java.lang.NullPointerException
                                                                                at chuangyuan.ycj.videolibrary.widget.VideoPlayerView$6.setTimePosition(VideoPlayerView.java:475)
                                                                                at chuangyuan.ycj.videolibrary.video.GestureVideoPlayer.showProgressDialog(GestureVideoPlayer.java:194)
                                                                                at chuangyuan.ycj.videolibrary.video.GestureVideoPlayer.access$300(GestureVideoPlayer.java:38)
                                                                                at chuangyuan.ycj.videolibrary.video.GestureVideoPlayer$PlayerGestureListener.onScroll(GestureVideoPlayer.java:336)
                                                                                at android.view.GestureDetector.onTouchEvent(GestureDetector.java:567)
                                                                                at chuangyuan.ycj.videolibrary.video.GestureVideoPlayer.onTouch(GestureVideoPlayer.java:131)
                                                                                at android.view.View.dispatchTouchEvent(View.java:7701)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
                                                                                at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
                                                                                at android.view.View.dispatchPointerEvent(View.java:7886)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3978)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3857)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3423)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3473)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3442)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3549)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3450)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3606)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3423)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3473)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3442)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3450)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3423)
                                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5626)
                                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5606)
                                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5577)
                                                                                at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5706)
                                                                                at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5679)
                                                                                at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5725)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                            	at android

**Comment by wsty** [comment]
请问这是什么原因？

**Comment by yangchaojiang** [comment]
请更新到版本1.9.8

**Comment by yangchaojiang** [comment]
exoPlayerManager.setOnGestureBrightnessListener();
exoPlayerManager.setOnGestureProgressListener();
 exoPlayerManager.setOnGestureVolumeListener();

**Comment by yangchaojiang** [comment]
实现你自定义监听。请看自定义布局使用说明
