### ISSUE TITLE
华为手机的录音MP3格式无法播放，苹果录音caf格式无法播放，提示播放路径错误

### ISSUE THREAD

**Issue by Leavds** [yangchaojiang/yjPlay#45]
大神这两个音频的播放能加上么

**Comment by yangchaojiang** [comment]
请提供详情一点错误日志。MP3编码没有问题。都是播放的， 本地文件注意是读取sd权限申请。

**Comment by yangchaojiang** [comment]
请检查路径是否正确和权限。

**Comment by yangchaojiang** [comment]
caf 格式 一般都在苹果播放, 你们Android和ios 两端的话。ios 录制  转码MP3，aac,amr 等通用音频格式，我们已经都是处理的。

**Comment by Leavds** [comment]
![qq 20171218103913](https://user-images.githubusercontent.com/26810069/34087696-be2bd886-e3df-11e7-9d44-f4ca0fc7e8d0.png)
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:784)
                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:707)
                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:776)
![qq 20171218103756](https://user-images.githubusercontent.com/26810069/34087675-96282a24-e3df-11e7-82fa-245ab245bd34.png)

**Comment by Leavds** [comment]
华为的手机录的MP3 ， 无法用播放报这个错误，其他手机录的目前都正常，就华为录的不行

**Comment by JamChanGitHub** [comment]
ExoPlayerImplInternal: Internal runtime error.
                                                                                    java.lang.IllegalStateException
                                                                                        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                                        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:631)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:179)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

切换横竖屏报这个错，请问下什么问题
