### ISSUE TITLE
多次切换url

### ISSUE THREAD

**Issue by marscl** [yangchaojiang/yjPlay#63]
是多次使用 exoPlayerManager.setPlayUri("XXXXX")吗 有时播放失效

**Comment by marscl** [comment]
01-15 21:17:30.770 3130-3502/com.marsvideo E/ExoPlayerImplInternal: Source error.
                                                                    com.google.android.exoplayer2.source.BehindLiveWindowException
                                                                        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:280)
                                                                        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:466)
                                                                        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:71)
                                                                        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:194)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.continueLoading(ExoPlayerImplInternal.java:1640)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1439)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1432)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:334)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                        at android.os.Looper.loop(Looper.java:203)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
01-15 21:17:30.771 3130-3502/com.marsvideo I/MediaCodec: [stop]line:664 [OMX.MTK.VIDEO.DECODER.AVC]+++
01-15 21:17:30.778 3130-3130/com.marsvideo E/chuangyuan.ycj.videolibrary.video.ExoUserPlayer: onPlayerError:null

**Comment by yangchaojiang** [comment]
版本是1.9.93 吗？

**Comment by marscl** [comment]
是的

**Comment by yangchaojiang** [comment]
看了日志，你是怎么释放资源，重来加载 uri

**Comment by marscl** [comment]
重复setUrl  然后startPlay

**Comment by yangchaojiang** [comment]
setur之前，i先释放哦。

**Comment by yangchaojiang** [comment]
你可以参考一下啊https://github.com/yangchaojiang/yjPlay/issues/60  一样问题。

**Comment by yangchaojiang** [comment]
你可以参考一下,https://github.com/yangchaojiang/yjPlay/issues/60 一样问题。

**Comment by marscl** [comment]
WholeMediaSource mediaSourceBuilder;
if(exoPlayerManager!=null&&mediaSourceBuilder!=null){
                    mediaSourceBuilder.release();
                    mediaSourceBuilder.setMediaUri(Uri.parse(msg.getData().getString("url")));
                    exoPlayerManager.startPlayer();
                }
还是会报上面的错
