### ISSUE TITLE
播放MP4出错

### ISSUE THREAD

**Issue by MIkeeJY** [yangchaojiang/yjPlay#89]
DEMO直接可以复现 
    private String url = " https://aweme.snssdk.com/aweme/v1/play/?video_id=303aba9d42b8492dbf7008b7ec1d6f72&line=0&ratio=720p&media_type=4&vr_type=0&test_cdn=None&improve_bitrate=0";

E/ExoPlayerImplInternal: Source error.
                                                                                     com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
                                                                                         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
                                                                                         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
                                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
                                                                                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                         at java.lang.Thread.run(Thread.java:762)

**Comment by yangchaojiang** [comment]
完整播放视频流的流。不支持加密片段

**Comment by MIkeeJY** [comment]
如何解决呢？这应该是google EXO默认不支持哦是吗？

**Comment by yangchaojiang** [comment]
理解住错误主要视频链接重定向.了
 //默认数据源工厂
 
// true 支持支持重定向/ 默认时不支持。
```
public class Data2Source implements DataSourceListener {
    public static final String TAG = "OfficeDataSource";

    private Context context;

    public Data2Source(Context context) {
        this.context = context;
    }

    @Override
    public com.google.android.exoplayer2.upstream.DataSource.Factory getDataSourceFactory() {
        // OkHttpClient okHttpClient = new OkHttpClient();
        // OkHttpDataSourceFactory OkHttpDataSourceFactory=    new OkHttpDataSourceFactory(okHttpClient, Util.getUserAgent(context, context.getApplicationContext().getPackageName()),new DefaultBandwidthMeter() );
        //使用OkHttpClient 数据源工厂
        //   return  OkHttpDataSourceFactory;
        //默认数据源工厂
        return new DefaultHttpDataSourceFactory(context.getPackageName(),null ,DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,true);
        
    }
}
```

**Comment by MIkeeJY** [comment]
@yangchaojiang 已经解决.非常感谢
